{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f526e682-471f-4f32-a072-6a75330bd81a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Number Guessing Game\n"
     ]
    }
   ],
   "source": [
    "#!/usr/bin/env python3\n",
    "\"\"\"\n",
    "Number Guessing Game (<=100 lines)\n",
    "- Difficulty (easy/medium/hard)\n",
    "- Hints (very close / close / warm / cold)\n",
    "- Input validation and 'quit' to exit\n",
    "- Simple high score saved to 'ng_highscore.json' in current directory\n",
    "\"\"\"\n",
    "import random, time, json\n",
    "from pathlib import Path\n",
    "\n",
    "HS_FILE = Path(\"ng_highscore.json\")\n",
    "\n",
    "def load_highscore():\n",
    "\ttry:\n",
    "\t\treturn json.loads(HS_FILE.read_text()).get(\"best\")\n",
    "\texcept Exception:\n",
    "\t\treturn None\n",
    "\n",
    "def save_highscore(score):\n",
    "\ttry:\n",
    "\t\tHS_FILE.write_text(json.dumps({\"best\": score}))\n",
    "\texcept Exception:\n",
    "\t\tpass\n",
    "\n",
    "def choose_difficulty():\n",
    "\topts = {\"easy\": 15, \"medium\": 10, \"hard\": 5}\n",
    "\twhile True:\n",
    "\t\ts = input(\"Choose difficulty (easy/medium/hard) [medium]: \").strip().lower() or \"medium\"\n",
    "\t\tif s in opts:\n",
    "\t\t\treturn opts[s]\n",
    "\t\tprint(\"Type 'easy', 'medium', or 'hard'.\")\n",
    "\n",
    "def get_guess(low, high):\n",
    "\twhile True:\n",
    "\t\ts = input(f\"Enter your guess ({low}-{high}) or 'quit': \").strip().lower()\n",
    "\t\tif s == \"quit\":\n",
    "\t\t\treturn None\n",
    "\t\tif s.isdigit():\n",
    "\t\t\tg = int(s)\n",
    "\t\t\tif low <= g <= high:\n",
    "\t\t\t\treturn g\n",
    "\t\t\tprint(f\"Please pick a number between {low} and {high}.\")\n",
    "\t\telse:\n",
    "\t\t\tprint(\"Enter a whole number or 'quit'.\")\n",
    "\n",
    "def hint_for(secret, guess):\n",
    "\td = abs(secret - guess)\n",
    "\tif d == 0:\n",
    "\t\treturn \"correct\"\n",
    "\tif d <= 2:\n",
    "\t\treturn \"very close\"\n",
    "\tif d <= 5:\n",
    "\t\treturn \"close\"\n",
    "\tif d <= 10:\n",
    "\t\treturn \"warm\"\n",
    "\treturn \"cold\"\n",
    "\n",
    "def play_round():\n",
    "\tlow, high = 1, 100\n",
    "\tsecret = random.randint(low, high)\n",
    "\ttries = choose_difficulty()\n",
    "\tprint(f\"I chose a number between {low} and {high}. You have {tries} guesses.\")\n",
    "\tstart = time.time()\n",
    "\tattempts = 0\n",
    "\twhile attempts < tries:\n",
    "\t\tg = get_guess(low, high)\n",
    "\t\tif g is None:\n",
    "\t\t\tprint(\"Quitting this round.\")\n",
    "\t\t\treturn None\n",
    "\t\tattempts += 1\n",
    "\t\th = hint_for(secret, g)\n",
    "\t\tif h == \"correct\":\n",
    "\t\t\telapsed = int(time.time() - start)\n",
    "\t\t\tscore = max(0, 100 - attempts * 2 - elapsed)\n",
    "\t\t\tprint(f\"Correct! {g} in {attempts} guesses, {elapsed}s. Score: {score}\")\n",
    "\t\t\treturn score\n",
    "\t\tdir_msg = \"Too low.\" if g < secret else \"Too high.\"\n",
    "\t\tprint(f\"{dir_msg} ({h}) — guesses left: {tries - attempts}\")\n",
    "\tprint(f\"Out of guesses! The number was {secret}.\")\n",
    "\treturn 0\n",
    "\n",
    "def main():\n",
    "\tprint(\"Number Guessing Game\")\n",
    "\tbest = load_highscore()\n",
    "\tif best is not None:\n",
    "\t\tprint(f\"Current high score: {best}\")\n",
    "\twhile True:\n",
    "\t\tresult = play_round()\n",
    "\t\tif result is None:\n",
    "\t\t\tbreak\n",
    "\t\tif best is None or result > best:\n",
    "\t\t\tbest = result\n",
    "\t\t\tsave_highscore(best)\n",
    "\t\t\tprint(f\"New high score: {best} (saved)\")\n",
    "\t\tif input(\"Play again? (y/n): \").strip().lower() not in (\"y\", \"yes\"):\n",
    "\t\t\tbreak\n",
    "\tprint(\"Thanks for playing!\")\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "\ttry:\n",
    "\t\tmain()\n",
    "\texcept KeyboardInterrupt:\n",
    "\t\tprint(\"\\nGoodbye.\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "42d73740-4ed2-4692-9ecd-c944118b9b4c",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
